name: Modificar README con Meme

on:
  push:
    branches:
      - github_action_readme

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-24.04
    outputs:
      resultat_tests: ${{ steps.test.outcome }}

    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install

      - name: Ejecutar tests
        run: |
          npm test
        id: test

      - name: Mostrar resultado de los tests
        id: set_output
        run: echo "resultat_tests=${{ steps.test.outcome }}" >> $GITHUB_ENV

  modificar_readme:
    runs-on: ubuntu-24.04
    needs: tests
    steps:
      - name: Revisar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install

      - name: Añadir meme al README
        uses: ./ # Apunta al directorio donde está la acción personalizada (action.yml)
        with:
          frase_positiva: "Los tests han funcionado y lo sabes."
          frase_negativa: "Los tests han fallado y lo sabes."
          resultat_tests: ${{ needs.tests.outputs.resultat_tests }}

      - name: Subir los cambios al repositorio
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
